- content/_index.md
> Fix Learn More Link

- content/posts/client-mpv.md
My phone automatically inserted smart quotes, which causes a parsing failure.
> Remove smart quotes from client-mpv.md

- content/posts/client-mpv.md
This fixes the line breaks between each sentence on https://jellyfin.org/posts/client-mpv/.
> Fix line breaks.

- config.yaml
- content/_index.md
- layouts/partials/landing_hero.html
Restores the scroll to the "Learn More" button, and updates the footer link to the correct repository.
> Minor page usage changes

- content/contact/_index.md
Also updated the dev-client as it still used an old name
> Add matrix android channel to contact page

- assets/sass/custom.style.scss
- content/clients/_index.md
Basically what it says in the title
> Add names to client page + improve layout

- .ci/azure-pipelines.yml
- .ci/publish-to-gh-pages.sh
This is pending a decision on the minification.
> Fix environment variable and pipeline error

- content/contribute/_index.md
Adds a brief message about the conversion to ES6 and Vue.
> Remove React mention and add current plan

- content/contribute/_index.md
Missed a variable when updating.
> Fix broken contribute button

- config.yaml
- layouts/partials/header.html
During a visit of the project's blog I realized there is no RSS feed available. This pull request adds support for RSS. Feel free to merge or comment (if further modification is necessary).
> Added RSS feed for blog posts

- content/downloads/_index.md
Explicitly mention what we support from the automagic sources.list
command so that people can better interpret "bad" output.
> Modify Debuntu install note to be clearer

- content/_index.md
> Add clients link, change contribute link

- content/posts/android-next.md
Draft status should be removed when the app is published
> Set android-next post as draft

- content/contribute/_index.md
Add links to the contributing guide and community standards.
Ref https://github.com/jellyfin/jellyfin-docs/pull/414
> Add links to contributing guide/standards

- content/clients/_index.md
- static/images/clients/sailfin.svg
This monochrome icon is the best I can make out of my normal icon.
I'm not sure if I should remove the outside shape of the icon, but most
of Sailfish OS applications are in this big shape, since it's what Jolla
recommends: https://sailfishos.org/content/uploads/2018/11/48_SAILFISH-APPS-ICON-STORY.pdf
Yes, graphic design is my passion :)
> Adds Sailfin to the list of clients

- content/posts/android-next.md
Since we're aiming to release the app tomorrow I'll open the PR now so we have some time to make some tweaks to the contents.
> Publish Android 2.0.0 post

- content/contact/_index.md
-Riot
+Element
+jellyfin-translate
> Update contact section

- content/downloads/_index.md
1. Add main to the unstable config
2. Add explanation of why
3. Add mention of the weird releases
> Fix some docs bugs

- content/posts/jellyfin-apt-key.md
Adds a post about the `apt` key update, to ensure maximum visibility even to those not on Reddit or Matrix.
> Add keyserver update post

- content/clients/_index.md
In App Store, [MrMC Touch](https://apps.apple.com/app/mrmc-touch/id1062986407) is iOS version, [MrMC](https://apps.apple.com/app/mrmc/id1059536415) is TV Version.
> Fix wrong link

- content/contact/_index.md
Removes Forum link, adds Discord with disclaimer.
> Revise Contact Item List

- content/clients/_index.md
This updates the link on the Jellyfin website to point to the new home for MPV Shim.
> Rename and update MPV Shim link.

- content/posts/mirrorbits-cdn.md
Adds a post about our Mirrorbits setup. Half informational, half practical documentation for Mirrorbits.
> Add post about Mirrorbits setup

- content/clients/_index.md
- static/images/clients/jellyfin-white.svg
A consideration with this PR is what icon Jellyfin Media Player should have. I copied the MPV one for now.
> Add Jellyfin Media Player.

- content/clients/_index.md
Renames "Jellyfin Desktop" back to "Jellyfin MPV Shim".
> Rename MPV Shim again.

- content/contact/_index.md
> Add Telegram

- content/contact/_index.md
> Move to Libera.chat

- content/posts/android-v2.4.0.md
To be merged once the release is live.
> Add release blog post for Jellyfin Android 2.4.0

- content/clients/_index.md
Didn't spot it in #114 until after I merged it. whoops!
> Add third-party subbanner for Sonixd

- content/contact/_index.md
Updates to include all channels, the Matrix Space, and missing IRC rooms.
> Update the Contact Page

- layouts/partials/header.html
> Use absolute urls in header.html

- content/posts/jellyfin-10-8-0.md
Do not merge until release (tomorrow at 8PM EDT).
> Add blog post for 10.8.0 release

- content/clients/_index.md
- content/posts/webos-july2022.md
Fix the clients page broken buttons, and some formatting fixes for the blog post.
> Fix clients page and formatting

- content/downloads/_index.md
(System76 OS)
More secure command as well that's more clear about what it actually does.
> Fix installation instructions for Pop! OS
